name: kashio_mobile
description: "Kashio - M-PESA SMS Reader & Sync"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  telephony: ^0.2.0
  dio: ^5.9.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  uuid: ^4.5.3
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true